# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-18 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0003_paymentmodel_paid_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='paid_count',
        ),
        migrations.AddField(
            model_name='subscriptionmodel',
            name='paid_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
