# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-19 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0005_auto_20171118_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
