# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0005_auto_20170611_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='featured_video',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='profile_description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='myuser',
            name='short_bio',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='myuser',
            name='social_links',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
