# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0006_auto_20170611_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
