# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0007_myuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='picture',
            field=models.ImageField(default='profile_images/profile_b.jpg', upload_to='profile_images'),
        ),
    ]
