# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0008_auto_20170617_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='category',
            field=models.CharField(choices=[('VIDOE & FILM', 'Amsterdam'), ('MUSIC', 'Rotterdam'), ('WRITING', 'The Hague'), ('ARTS & CRAFTS', 'Utrecht'), ('GAMES', 'Utrecht'), ('PHOTOGRAPHY', 'Utrecht'), ('SCIENCE', 'Utrecht'), ('EDUCATION', 'Utrecht'), ('DANCE & THEATER', 'Utrecht'), ('OPEN SOURCE', 'Utrecht'), ('OTHER', 'Utrecht')], default='OTHER', max_length=30),
        ),
    ]
