# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0008_auto_20171203_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='club_2_reward',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='myuser',
            name='club_3_reward',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='myuser',
            name='club_4_reward',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='category',
            field=models.CharField(choices=[('OTHERS', 'Others'), ('MUSIC', 'Music'), ('MEDIA', 'Media'), ('GAMES', 'Games'), ('COMEDY', 'Comedy'), ('WRITING', 'Writing'), ('PODCASTS', 'Podcasts'), ('EDUCATION', 'Education'), ('PHOTOGRAPHY', 'Photography'), ('PROGRAMMING', 'Programming'), ('CRAFTS AND DIY', 'Crafts and DIY'), ('VIDEOS AND FILMS', 'Videos and Films'), ('DANCE AND THEATER', 'Dance and Theater'), ('DRAWING AND PAINTING', 'Drawing and Painting'), ('SCIENCE AND TECHNOLOGY', 'Science and Technology')], default='Coding', max_length=30),
        ),
    ]
