# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0009_myuser_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='category',
            field=models.CharField(choices=[('OTHERS', 'Others'), ('VIDEOS AND FILMS', 'Videos and Films'), ('MUSIC', 'Music'), ('WRITING', 'Writing'), ('ARTS AND CRAFTS', 'Arts and Crafts'), ('GAMES', 'Games'), ('PHOTOGRAPHY', 'Photography'), ('SCIENCE AND TECHNOLOGY', 'Science and Technology'), ('EDUCATION', 'Education'), ('DANCE AND THEATER', 'Dance and Theater'), ('CODING', 'Coding')], default='Coding', max_length=30),
        ),
    ]
