# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0011_auto_20170630_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='featured_text',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
