# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0012_auto_20171214_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='status',
            field=models.CharField(choices=[('unknown', 'unknown'), ('created', 'created'), ('authenticated', 'authenticated'), ('active', 'active'), ('pending', 'pending'), ('halted', 'halted'), ('cancelled', 'cancelled'), ('completed', 'completed'), ('expired', 'expired')], default='unknown', max_length=30),
        ),
    ]
