# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-21 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0012_myuser_featured_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subs_from', models.CharField(max_length=20)),
                ('subs_to', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('unknown', 'unknown'), ('live', 'live'), ('trial', 'trial'), ('dunning', 'dunning'), ('unpaid', 'unpaid'), ('non_renewing', 'non_renewing'), ('cancelled', 'cancelled'), ('creation_failed', 'creation_failed'), ('cancelled_from_dunning', 'cancelled_from_dunning'), ('expired', 'expired'), ('trial_expired', 'trial_expired'), ('future', 'future')], default='unknown', max_length=30)),
                ('subs_channel', models.CharField(choices=[('NA', 'na'), ('ZOHO', 'zoho'), ('PAYTM', 'paytm')], default='NA', max_length=10)),
                ('amount', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField()),
            ],
        ),
    ]
