# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 12:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0013_auto_20171214_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionmodel',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 17, 12, 22, 30, 959073)),
            preserve_default=False,
        ),
    ]
