# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 06:46
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0013_subscriptionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='card_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='myuser',
            name='customer_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
