# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-27 10:45
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0014_auto_20170725_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='card_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
