# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-31 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0015_auto_20170727_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='featured_text',
            field=models.CharField(default='Thank you for your help!', max_length=1000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='featured_video',
            field=models.URLField(default='https://www.youtube.com/embed/oc_vB5Xcx1o'),
        ),
    ]
