# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-15 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0017_auto_20170815_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='ended_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
