# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0018_auto_20180329_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='featured_video',
            field=models.URLField(default='https://www.youtube.com/embed/caxNXMpQND4'),
        ),
    ]
