# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-15 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0019_auto_20170815_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionmodel',
            name='subscription_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
