# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 11:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0020_subscriptionmodel_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
