# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0020_remove_myuser_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='category',
            field=models.CharField(choices=[('OTHERS', 'Others'), ('MUSIC', 'Music'), ('MEDIA', 'Media'), ('GAMES', 'Games'), ('COMEDY', 'Comedy'), ('WRITING', 'Writing'), ('PODCASTS', 'Podcasts'), ('EDUCATION', 'Education'), ('PHOTOGRAPHY', 'Photography'), ('PROGRAMMING', 'Programming'), ('CRAFTS AND DIY', 'Crafts and DIY'), ('VIDEOS AND FILMS', 'Videos and Films'), ('DANCE AND THEATER', 'Dance and Theater'), ('DRAWING AND PAINTING', 'Drawing and Painting'), ('SCIENCE AND TECHNOLOGY', 'Science and Technology')], default='Others', max_length=30),
        ),
    ]
