# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0021_auto_20170821_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='featured_image',
            field=models.ImageField(default='featured_images/default_cover.jpg', upload_to='featured_images'),
        ),
    ]
