# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-29 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0025_auto_20170825_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='invoice_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='subscription_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
