# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-29 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0026_auto_20170829_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadumpmodel',
            name='event_type',
            field=models.CharField(max_length=100),
        ),
    ]
