# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 09:56
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0027_auto_20170829_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsPlanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('interval', models.DecimalField(decimal_places=2, max_digits=2)),
                ('period', models.CharField(max_length=20)),
                ('currency', models.CharField(blank=True, max_length=255)),
                ('notes', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_creator', to=settings.AUTH_USER_MODEL)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_subscriber', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subscriptionmodel',
            name='notes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='subs_channel',
            field=models.CharField(choices=[('NA', 'na'), ('ZOHO', 'zoho'), ('PAYTM', 'paytm'), ('RAZORPAY', 'razorpay')], default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='transaction_status',
            field=models.CharField(choices=[('paid', 'Amount paid'), ('waiting', 'Waiting for confirmation'), ('preauth', 'Pre-authorized'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('refunded', 'Refunded'), ('error', 'Error'), ('input', 'Input')], default='waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionmodel',
            name='plan',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='plan', to='regapp.SubsPlanModel'),
            preserve_default=False,
        ),
    ]
