# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 11:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0030_auto_20171005_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='notes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
