# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-07 10:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0032_auto_20171005_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='subsplanmodel',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='subsplanmodel',
            name='currency',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='subsplanmodel',
            name='interval',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subsplanmodel',
            name='period',
            field=models.CharField(default='monthly', max_length=10),
        ),
    ]
