# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-12 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0033_auto_20171007_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
